-- ===== VIVÊNCIA — adapt schema + demo content =====

alter table public.experiences alter column host_id drop not null;
alter table public.experiences add column if not exists featured boolean not null default false;

delete from public.experiences where host_id is null;

insert into public.experiences
  (host_id, host_name, title, category, region, location, price, duration_hrs, group_max, summary, descr, inc, img, gallery, rating, reviews, status, featured)
values
(null, $$Tiago Andrade$$, $$Private Sunset Yacht Cruise$$, $$ocean$$, $$Funchal$$, $$Funchal Marina$$, 95, 3, 8, $$Sail the south coast at golden hour with welcome drinks and a swim stop in a hidden bay.$$, ARRAY[$$Step aboard a private sailing yacht as the light turns over the Atlantic. We leave Funchal Marina, hug the cliffs toward Câmara de Lobos and drop anchor in a calm bay where you can swim straight off the deck.$$,$$Madeira poncha and local snacks are served as the sun sets behind the headland. This is a small group sailing, never more than eight guests, so it feels like your own boat for the evening.$$]::text[], ARRAY[$$Skipper and crew$$,$$Welcome poncha and snacks$$,$$Snorkel gear$$,$$Towels on board$$,$$Hotel pickup in central Funchal$$]::text[], $$img/yacht-sunset.jpg$$, ARRAY[$$img/yacht-cruise.jpg$$,$$img/coast-turquoise.jpg$$]::text[], 4.62, 48, 'live', false),
(null, $$Inês Carvalho$$, $$Levada das 25 Fontes Guided Walk$$, $$nature$$, $$Calheta$$, $$Rabaçal$$, 48, 5, 10, $$Walk the laurel forest to a waterfall amphitheatre fed by twenty five springs.$$, ARRAY[$$One of the most beautiful trails on the island. We follow a centuries old water channel through dense laurissilva, a forest so rare it carries UNESCO protection.$$,$$The path opens onto a natural amphitheatre where dozens of springs pour down the rock face. Your guide reads the landscape for you, the endemic plants, the birds, the way the water shaped the island.$$]::text[], ARRAY[$$Certified mountain guide$$,$$Transfer to and from the trailhead$$,$$Walking poles$$,$$Light snack and water$$,$$Group photos$$]::text[], $$img/green-gorge.jpg$$, ARRAY[$$img/seixal-cliff.jpg$$,$$img/coastal-cliff.jpg$$]::text[], 4.69, 67, 'live', false),
(null, $$Rui Bettencourt$$, $$Madeira Wine Cellar Tasting$$, $$food$$, $$Funchal$$, $$Funchal Old Town$$, 65, 2.5, 12, $$Six pours of true Madeira wine in a historic Funchal lodge, with a guide who actually makes it.$$, ARRAY[$$Step into a centuries old lodge in the heart of Funchal where Madeira wine ages slowly under the island sun. We taste six expressions, from crisp dry Sercial to a deep sweet Malmsey, each one explained without the usual jargon.$$,$$You will learn how the volcanic soil, the grape varieties and the estufagem ageing build that unmistakable flavour. Local cheese and honey cake are paired throughout.$$]::text[], ARRAY[$$Six Madeira wine tasting$$,$$Local cheese and honey cake$$,$$Lodge tour$$,$$Expert sommelier host$$]::text[], $$https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=70$$, ARRAY[$$https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1000&q=70$$,$$https://images.unsplash.com/photo-1474722883778-792e7990302f?auto=format&fit=crop&w=1000&q=70$$]::text[], 4.76, 86, 'live', false),
(null, $$Tiago Andrade$$, $$Dolphin & Whale Watching by Catamaran$$, $$ocean$$, $$Calheta$$, $$Calheta$$, 58, 3, 14, $$Head into deep water with a marine biologist to find resident dolphins and whales.$$, ARRAY[$$Madeira sits on a migration corridor, which means resident pods of dolphins and seasonal whales. We sail from Calheta with a marine biologist on board who tracks them responsibly.$$,$$You keep a respectful distance, the engines go quiet, and you watch them move through clear blue water. Sightings are common all year.$$]::text[], ARRAY[$$Marine biologist guide$$,$$Catamaran with sun deck$$,$$Drinks on board$$,$$Sighting briefing$$]::text[], $$img/catamaran.jpg$$, ARRAY[$$img/coast-turquoise.jpg$$,$$img/yacht-cruise.jpg$$]::text[], 4.83, 105, 'live', false),
(null, $$Rui Bettencourt$$, $$Funchal Old Town Food & Poncha Crawl$$, $$food$$, $$Funchal$$, $$Zona Velha$$, 54, 3.5, 10, $$Eight tastings through the old town, from bolo do caco to espetada to a closing poncha.$$, ARRAY[$$We wind through the Zona Velha, the oldest quarter of Funchal, stopping at the places locals actually queue for. Warm bolo do caco with garlic butter, fresh limpets, skewered espetada straight off the laurel stick.$$,$$Between bites you get the story of the neighbourhood, the painted doors, the market and the fishermen. We finish with a proper poncha in a tiny back street bar.$$]::text[], ARRAY[$$Eight food and drink tastings$$,$$Local guide$$,$$All gratuities$$,$$Small group$$]::text[], $$https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=1000&q=70$$, ARRAY[$$https://images.unsplash.com/photo-1513735492246-483525079686?auto=format&fit=crop&w=1000&q=70$$]::text[], 4.90, 124, 'live', false),
(null, $$Inês Carvalho$$, $$Pico do Arieiro Sunrise Hike$$, $$adventure$$, $$Santana$$, $$Pico do Arieiro$$, 72, 6, 8, $$Start before dawn on the third highest peak and walk the ridge above the clouds.$$, ARRAY[$$We meet in the dark and drive to the summit for first light. From 1818 metres you stand above a sea of cloud as the sun breaks over the eastern ridge.$$,$$From there we take the stairway ridge toward Pico Ruivo, one of the great alpine walks in Europe. Steep in places, fully guided, unforgettable.$$]::text[], ARRAY[$$Pre dawn pickup$$,$$Mountain guide$$,$$Headlamp and poles$$,$$Breakfast at the summit$$,$$Safety equipment$$]::text[], $$img/peaks.jpg$$, ARRAY[$$img/green-gorge.jpg$$,$$img/seixal-cliff.jpg$$]::text[], 4.62, 143, 'live', false),
(null, $$Rui Bettencourt$$, $$Monte, Toboggan & Funchal Heritage Day$$, $$culture$$, $$Funchal$$, $$Monte$$, 78, 6, 6, $$Ride the cable car to Monte, take the wicker toboggan down, then walk old Funchal with a local historian.$$, ARRAY[$$We climb high above the bay in the Funchal cable car to the village of Monte, with its baroque church and tropical gardens. Then the famous carro de cesto, the wicker toboggan steered downhill by two carreiros in straw hats and white linen.$$,$$Back in the city a local historian walks you through the cathedral, the old streets and the painted doors of the Zona Velha, the kings, the trade and the stories behind it all.$$]::text[], ARRAY[$$Private local historian$$,$$Cable car ticket$$,$$Toboggan ride$$,$$Air conditioned transport$$,$$Bottled water$$]::text[], $$img/coastal-town.jpg$$, ARRAY[$$img/pier.jpg$$,$$img/natural-pool.jpg$$]::text[], 4.69, 162, 'live', false),
(null, $$Tiago Andrade$$, $$Coastal Kayak & Sea Cave Tour$$, $$adventure$$, $$Funchal$$, $$Garajau$$, 42, 2, 8, $$Paddle into volcanic sea caves inside a protected marine reserve.$$, ARRAY[$$Launch from the Garajau reserve and paddle along black volcanic cliffs into hidden sea caves. The water here is protected, so the marine life is rich and the visibility is excellent.$$,$$No experience needed, full briefing included, and a snorkel stop over the reef before you head back.$$]::text[], ARRAY[$$Kayak and full gear$$,$$Guide and safety brief$$,$$Snorkel stop$$,$$Waterproof bag$$]::text[], $$img/coastal-cliff.jpg$$, ARRAY[$$img/coast-turquoise.jpg$$,$$img/natural-pool.jpg$$]::text[], 4.76, 181, 'live', false),
(null, $$Tiago Andrade$$, $$Private Boat Tour & Dolphin Safari$$, $$ocean$$, $$Funchal$$, $$Funchal Marina$$, 165, 3, 8, $$Your own private boat to find dolphins and whales, with swim stops in turquoise water.$$, ARRAY[$$Charter the whole boat for your group and head out with a skipper who knows exactly where the resident pods feed. The engines go quiet as you watch dolphins, and seasonal whales, move through clear Atlantic water.$$,$$We anchor in a calm bay for a swim and a snorkel, with drinks and Madeira poncha on board. Fully private, fully flexible, it is your afternoon on the water.$$]::text[], ARRAY[$$Private boat and skipper$$,$$Dolphin and whale spotting$$,$$Swim and snorkel stop$$,$$Drinks and poncha$$,$$Hotel pickup in central Funchal$$]::text[], $$img/catamaran.jpg$$, ARRAY[$$img/coast-turquoise.jpg$$,$$img/yacht-cruise.jpg$$]::text[], 4.83, 200, 'live', true),
(null, $$Inês Carvalho$$, $$4x4 Jeep Safari: Peaks & the Wild West$$, $$adventure$$, $$Calheta$$, $$Funchal (pickup)$$, 110, 7, 6, $$Off-road across the mountains, the laurel forest and the dramatic northwest coast.$$, ARRAY[$$A full day off the beaten track in a 4x4. We climb to the high peaks for views above the clouds, cross the ancient laurel forest and drop down to the wild northwest, with stops at viewpoints most tours never reach.$$,$$Your guide handles the driving and the stories, the geology, the legends, the best photo spots, while you just take it in. Lunch in a mountain village is included.$$]::text[], ARRAY[$$Private 4x4 and driver-guide$$,$$Hotel pickup and drop-off$$,$$Mountain village lunch$$,$$Viewpoints and short walks$$,$$Water and snacks$$]::text[], $$img/peaks.jpg$$, ARRAY[$$img/green-gorge.jpg$$,$$img/seixal-cliff.jpg$$]::text[], 4.90, 219, 'live', true),
(null, $$Tiago Andrade$$, $$Private Sunset Catamaran & Swim$$, $$ocean$$, $$Funchal$$, $$Funchal Marina$$, 130, 3, 10, $$Charter a catamaran for golden hour, with a swim stop and drinks as the sun goes down.$$, ARRAY[$$Step aboard a spacious catamaran reserved just for your group as the light turns gold over the Atlantic. We cruise the south coast and drop anchor in a quiet bay where you swim straight off the deck.$$,$$Sparkling wine, poncha and snacks are served while the sun sinks behind the headland. Smooth, private and unforgettable.$$]::text[], ARRAY[$$Private catamaran and crew$$,$$Sparkling wine and poncha$$,$$Swim and snorkel gear$$,$$Towels on board$$,$$Hotel pickup in central Funchal$$]::text[], $$img/yacht-sunset.jpg$$, ARRAY[$$img/coast-turquoise.jpg$$,$$img/yacht-cruise.jpg$$]::text[], 4.62, 238, 'live', true);

-- allow admins to update any profile (verify/reject hosts)
drop policy if exists p_upd_admin on public.profiles;
create policy p_upd_admin on public.profiles for update using (public.is_admin()) with check (public.is_admin());
